### ISSUE TITLE
Accessing other fields in derive and map?

### ISSUE THREAD

**Issue by joerichsen** [acalejos/flint#9]
Hi

I am experimenting with Flint and it looks great :-)

One question: I am experimenting with a Book schema stored in the database, where I have a published_on date field that I want to be able to let the user edit in three separate input fields in a form. So something like this

```
  defmodule Form do
    use Flint.Schema

    embedded_schema do
      field! :title, :string

      field! :published_on, :integer,
        map: fn -> Date.new!(published_year, published_month, published_day) end

      field! :published_day, :integer, derive: published_on.day
      field! :published_month, :integer, derive: published_on.month
      field! :published_year, :integer, derive: published_on.year
    end
  end

  def render(assigns) do
    ~H"""
    <h1>New Book</h1>
    <.form for={@form} phx-change="validate" phx-submit="save">
      <.input field={@form[:title]} />
      <.input field={@form[:published_day]} />
      <.input field={@form[:published_month]} />
      <.input field={@form[:published_year]} />
      <.button type="submit">Save</.button>
    </.form>
    """
  end

  def mount(_params, _session, socket) do
    form = %Form{} |> Form.changeset(%{}) |> to_form()
    {:ok, assign(socket, form: form)}
  end
```

so basically a two-way sync between the published_on field and the published_day, published_month, and published_year fields.

Can I do that with map and reduce like in the example? Or is there a better way?

This is the stacktrace I am getting right now:

```
iex(7)> published_on.year    error: undefined variable "published_on"
    │
 16 │       field! :published_day, :integer, derive: published_on.day
    │                                                ^^^^^^^^^^^^
    │
    └─ (flint_demo 0.1.0) lib/flint_demo_web/live/book_live.ex:16:48: FlintDemoWeb.BookLive.Form.Env.env/0

[info] Sent 500 in 262ms
[error] ** (CompileError) lib/flint_demo_web/live/book_live.ex: cannot compile file (errors have been logged)
    (elixir 1.17.3) src/elixir_expand.erl:422: :elixir_expand.expand/3
    (elixir 1.17.3) src/elixir_expand.erl:440: :elixir_expand.expand/3
    (elixir 1.17.3) src/elixir.erl:455: :elixir.quoted_to_erl/4
    (elixir 1.17.3) src/elixir.erl:332: :elixir.eval_forms/4
    (elixir 1.17.3) lib/module/parallel_checker.ex:112: Module.ParallelChecker.verify/1
    (elixir 1.17.3) lib/code.ex:1052: Code.eval_quoted/3
    (flint 0.5.0) lib/flint/extensions/pre_transforms.ex:70: anonymous fn/4 in Flint.Extensions.PreTransforms.apply_pre_transforms/2
    (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (flint_demo 0.1.0) lib/flint_demo_web/live/book_live.ex:8: FlintDemoWeb.BookLive.Form."changeset (overridable 3)"/3
    (flint_demo 0.1.0) lib/flint_demo_web/live/book_live.ex:8: FlintDemoWeb.BookLive.Form."changeset (overridable 4)"/3
    (flint_demo 0.1.0) lib/flint_demo_web/live/book_live.ex:8: FlintDemoWeb.BookLive.Form.changeset/3
    (flint_demo 0.1.0) lib/flint_demo_web/live/book_live.ex:36: FlintDemoWeb.BookLive.mount/3
...
```

I have pushed the code to this repo https://github.com/joerichsen/flint_demo

**Comment by acalejos** [comment]
```elixir
defmodule Form do
  use Flint.Schema

  embedded_schema do
    field(:published_on, :integer,
      derive: fn -> Date.new!(published_year, published_month, published_day) end
    )
    field!(:title, :string)
    field!(:published_day, :integer, map: published_on.day)
    field!(:published_month, :integer, map: published_on.month)
    field!(:published_year, :integer, map: published_on.year)
  end
end
```

You can try this out, although I'm not sure how the 2-way sync looks with this.

It might make more sense to use one of the date types built into Ecto

**Comment by joerichsen** [comment]
Thank you for responding so quickly. After thinking about it, Flint seems to be a great fit for letting the user fill in a form with validations, but I was also trying to map the form data back to a database backed schema and was thinking that prepare/map might also fit that scenario. I think I have to approach that problem in a different way.
